### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by kaivanmehta14** [msanvarov/nest-rest-typeorm-boilerplate#465]
does it support postgreSQL?

**Comment by msanvarov** [comment]
Yup it does. You can change up the settings by following the guide here https://typeorm.io/#/using-ormconfig

**Comment by msanvarov** [comment]
Please refer to this part of the [README](https://github.com/msanvarov/nest-rest-typeorm-boilerplate#-choosing-a-database) for changing databases. Remember, to modify the `.env` file of `DB_TYPE` to be `postgres`, `DB_PORT` to `5432` and download the postgreSQL client via `npm install pg`
