### ISSUE TITLE
[NewBie] Help in running typeorm config json

### ISSUE THREAD

**Issue by raviten** [msanvarov/nest-rest-typeorm-boilerplate#873]
I am trying to run typeorm config using the below configuration
    "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/modules/app/app.module.ts"

Should i use different ormconfig.json file managing environment?
How to run migrations safely in the production?

Can you please help., Thanks in Advance!!!

**Comment by micalevisk** [comment]
it won't work because `app.module.ts` doesn't exports a valid typeorm config. `typeorm` didn't know `@nestjs/typeorm`

**Comment by msanvarov** [comment]
TypeORM can be configured via environment variables. Refer to https://github.com/msanvarov/nest-rest-typeorm-boilerplate/issues/465 for examples on how to do so.
